[package]
name = "test_fltk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1"

[build-dependencies]
fl2rust = { path = "d:\\projects\\rust\\fl2rust-main", version = "0.4" }
